version: 2

sources:
  - name: raw_banking
    database: DBT_DATAVAULT    
    schema: RAW
    tables:
      - name: RAW_BANK_ACCOUNTS
      - name: RAW_TRANSACTIONS
      - name: RAW_BANK_CUSTOMER